### ISSUE TITLE
Sum coefficients for the same variable

### ISSUE THREAD

**Issue by SteveDiamond** [jacklzhu/CVXcanon#9]
Instead of keeping a vector of matrices for each variable id, you should sum them all and keep a single matrix. Someone recently posted on the CVXPY google group about canonicalization using a ton of memory. This should help with that.

**Comment by millerjohnp** [comment]
Hi Steven, 

We just updated the matrix building algorithm to perform summation over the coefficient matrices rather than keeping them as a vector. This modification is included in the new release and distribution on pypi. 

Do you happen to have the problem instance where canonicalization was using a ton of memory so that we can get a sense of the impact of this switch on memory usage?

Thanks!
John

**Comment by SteveDiamond** [comment]
I've emailed the person who had this problem. Hopefully he will send us the script that was using so much memory.
